---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: simplewebapp
        image: hoonieregistry.azurecr.io/simplewebapp:latest
        ports:
        - containerPort: 80