---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
  - port: 8765
    targetPort: 9376
  externalTrafficPolicy: Local
  selector:
    app: webapp